### PR TITLE
Adding support for Realistic voices using the Eleven labs API

### PR DESCRIPTION
**Pull request by kariuki-kithinji**
only supports voice generation

### CODE REVIEW

**Comment by osolmaz** [comment]
Thank you for the PR, it was on my roadmap to add support for Eleven Labs. I'm glad someone beat me to it. I'll go over this soon.

In the meanwhile, would you be willing to add an example and documentation along the lines of other services?

**Comment by kariuki-kithinji** [comment]
yeah that's doable , let me work on it but i mat be late but not until tomorrow

**Comment by mohit2152sharma** [comment]
Hey @osolmaz / @kariuki-kithinji , can we get this merged? If there is something blocking it, I am happy to contribute to it.

**Comment by mohit2152sharma** [comment]
Hey @osolmaz , I have created a new PR: #83 with some modification and better parameter support. Added example also

**Comment by osolmaz** [comment]
#83 implemented this

**Pull request closed without merging**
