### PR TITLE
Add Elevenlabs service

### PR DESCRIPTION
**Pull request by mohit2152sharma**
Added support for elevenlabs, with better parameter support. Have the option to select voice based on `voice_name` or `voice_id`. Also change the settings of voice using `voice_settings` parameter. 

Remaining tasks:

- [x] Add doc of `ElevenLabsService` to https://github.com/ManimCommunity/manim-voiceover/blob/main/docs/source/services.rst
- [x] Double check whether ElevenLabs API returns word boundaries

### CODE REVIEW

**Comment by osolmaz** [comment]
@mohit2152sharma I improved caching behavior and enabled transcription with Whisper by default. This is necessary to use bookmarks.

Can you check whether Elevenlabs API returns word boundaries (timestamps for beginning of each word in the audio)? I looked briefly and couldn't see it, but I feel like it might be hidden somewhere.

**Review by osolmaz — CHANGES_REQUESTED** [review]
I've added remaining tasks to your first post, also see my comments.

**Comment by mohit2152sharma** [comment]
@osolmaz , I added the documentation. For the bookmark part, it wasn't working for me until i changed `"voice_settings": self.voice.model_dump(exclude_none=True)`. (I tested it with `examples/bookmark-example.py` setting `ElevenlabsService`)

Regarding caching I assumed that it was a bug as it wasn't respecting the `--disable_caching` flag. But after using elvenlabs  for couple of days, I have realised now that it was a good behaviour. Thanks for reverting it.

**Comment by osolmaz** [comment]
I just ran the bookmark example using the default voice, the quality out of the box is insane.

You could get to something very reasonable with a little tweaking.

https://github.com/ManimCommunity/manim-voiceover/assets/2453968/9422daed-a3c6-4e12-a0c1-2b3dd711704f

**Comment by osolmaz** [comment]
Btw `--disable_caching` is necesssary because of a Manim bug with adding sound.

**Pull request merged**
